### ISSUE TITLE
not working with py3: pack/unpack works with byte arrays instead of strings

### ISSUE THREAD

**Issue by ckolumbus** [braingram/comando#5]
Hi, is this project still actively maintained? and if so, are the any plans to port this to py3? would be great to see this working on py3 as well!
Chris

**Comment by braingram** [comment]
Hi Chris,

I'm definitely still using this project. However, all the systems I'm using it in are stuck in python 2 for various reasons. I'd be glad to hear what you think might be needed to make it py3 compliant and/or review a pull request. Hopefully it's still useful in it's current state :)

--
Thanks,
Brett

**Comment by ckolumbus** [comment]
I got the command.py example completely running under py3,  only the EventManager cause some headaches :-). PR for the current work is on the way, feedback is welcome!!!
